name: Main CI Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        name: Use Node.js ${{ matrix.node-version }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install
        run: yarn install

      - name: Type Check
        run: yarn tsc

      - name: Lint
        run: yarn lint

      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: './docker-compose.yml'

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
